platform :ios,'7.0'
pod 'SDWebImage'
pod 'AFNetworking','~>3.0.4'
pod 'MJRefresh'
pod 'AMapLocation', '~> 1.2.0'
pod 'AMap2DMap', '~> 3.3.0'
pod 'AMapSearch', '~> 3.3.0'
pod 'SVProgressHUD', '~> 1.1.2'
pod 'FMDB', '~> 2.5'
pod 'CocoaLumberjack', '~> 2.0.0-rc2'


